[package]
name = "jess"
version = "0.1.0"
authors = ["acrockett <adam.crockett@dyson.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/lib-jess.rs"

[dependencies]
wasm-bindgen = "0.2.56"
nom = "5.0.1"
js-sys = "0.3.33"
regex = "1.3.1"
enquote = "1.0.3"